live_config_reload = true

[font]
size = 9.0

[font.normal]
family = "FiraMono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[window]
decorations = "full"
opacity = 0.9
