add_newline = true

[aws.region_aliases]
af-south-1 = "capetown"
ap-southeast-2 = "sydney"
eu-west-1 = "london"
us-east-1 = "virginia"

[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 10000

[hostname]
disabled = false
ssh_only = false

[kubernetes]
disabled = false

[localip]
disabled = false
ssh_only = false

[package]
disabled = true
