icons_format = "{icon}"

[theme]
theme = "modern" # "solarized-dark"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "custom"
command = "echo \uf030" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "flameshot gui --delay 2000"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:40,rot_interval:0.5) $play $next |}"

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 100.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# headset
[[block]]
block = "bluetooth"
mac = "38:18:4C:BD:1B:16"
merge_with_next = true
if_command = "bluetoothctl devices Connected | grep 38:18:4C:BD:1B:16"

# speaker
[[block]]
block = "bluetooth"
mac = "10:28:74:D9:4E:E5"
if_command = "bluetoothctl devices Connected | grep 10:28:74:D9:4E:E5"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
